version: '3.4'

services:
  fastapi:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    networks: 
      - potatonet
      
  interface:
    build:
      context: ./interface
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - potatonet

networks:
  potatonet: